# cassandra_connector.py
from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import json
# Global variable to store the Cassandra session

cassandra_session = None


def establish_connection():
    global cassandra_session
    if cassandra_session is None:
        cloud_config = {
            'secure_connect_bundle': '/home/roy/airflow/dags/binance_etl/secure-connect-crypto.zip'
        }

        # This token JSON file is autogenerated when you download your token,
        # if yours is different update the file name below
        with open("/home/roy/airflow/dags/binance_etl/crypto-token.json") as f:
            secrets = json.load(f)

        CLIENT_ID = secrets["clientId"]
        CLIENT_SECRET = secrets["secret"]

        auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
        cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
        cassandra_session = cluster.connect()
    return cassandra_session

